type FaceKind = "eye" | "cheek" | "mouth" | "ear";

type ComponentGeometry = {
  pixels: number[];
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
  centerX: number;
  centerY: number;
};

type LinearGate = {
  threshold: number;
  mean: readonly number[];
  scale: readonly number[];
  coefficient: readonly number[];
  intercept: number;
};

// Generated by ml/train_component_gate_v5.py from 700 validation drawings;
// the remaining 300 selected thresholds. Eye and mouth intentionally remain
// unfiltered because their existing browser F1 already exceeds 0.92.
const GATES: Partial<Record<FaceKind, LinearGate>> = {
  cheek: {
    threshold: 0.24,
    mean: [3.81584076, 0.00673229, 0.11569186, 0.07136824, 0.46685445, 0.61647847, 0.49238029, 0.54946644, 0.20474371, 0, 0.41670617, 0.19079907, 0.62168359, 0.13272113, 0.31207238, 0.52387292, 0.50237319, 0.34277294, 0.65401461, 0.57455599, 0.38738739, 0.44444445],
    scale: [1.30247468, 0.01109059, 0.10495116, 0.05575531, 0.59796553, 0.1688797, 0.18300562, 0.10630216, 0.0733226, 1, 0.19149723, 0.00971472, 0.28627791, 0.09138309, 0.15242702, 0.26682149, 0.32982799, 0.27577186, 0.33486517, 0.27523253, 0.43709654, 0.24103893],
    coefficient: [0.00403771, 0.17381602, 0.05342817, 0.00069409, -0.06443209, 0.04153338, 0.08255999, 0.22547952, 0.09401783, 0, 0.09379817, 0.13814674, 0.13249282, 0.12149478, 0.21460755, 0.08376912, 0.04134882, -0.14471721, 0.32145679, -0.12055274, 0.16843068, 0.16370095],
    intercept: -0.17449845,
  },
  ear: {
    threshold: 0.26,
    mean: [4.94242268, 0.01555278, 0.12150438, 0.15372305, -0.24122181, 0.6703229, 0.48875, 0.36311943, 0.33265521, 0.00539084, 0.88916966, 0.69489042, 0.94986525, 0.0605373, 0.8677914, 0.92980983, 0.71266018, 0.76257302, 0.88575501, 0.28330398, 0.39622642, 0.34456425],
    scale: [1.25090779, 0.01575848, 0.0740845, 0.08522449, 0.35834178, 0.1151531, 0.27531001, 0.14592565, 0.0727548, 0.07322414, 0.08635267, 0.00891855, 0.07524695, 0.01754625, 0.10398839, 0.08715735, 0.32141647, 0.26703046, 0.18528347, 0.27042892, 0.47062321, 0.13987634],
    coefficient: [0.02272848, -0.04946954, -0.07385284, 0.07035962, -0.07060667, -0.12563481, -0.10337899, 0.29612409, -0.06752676, -0.01994152, 0.32182032, 0.01766085, 0.12251261, -0.22437174, 0.45437061, 0.16098253, 0.11868804, 0.10207201, 0.23938379, -0.09665152, 0.40952881, 0.01316252],
    intercept: 0.1626283,
  },
};

const sigmoid = (value: number) => 1 / (1 + Math.exp(-value));

function quantile(sorted: readonly number[], fraction: number) {
  if (!sorted.length) return 0;
  const position = (sorted.length - 1) * fraction;
  const lower = Math.floor(position);
  const upper = Math.ceil(position);
  const mix = position - lower;
  return sorted[lower] * (1 - mix) + sorted[upper] * mix;
}

function distribution(values: readonly number[]) {
  const mean = values.reduce((total, value) => total + value, 0) / Math.max(1, values.length);
  const variance = values.reduce((total, value) => total + (value - mean) ** 2, 0) / Math.max(1, values.length);
  const sorted = [...values].sort((a, b) => a - b);
  return {
    mean,
    minimum: sorted[0] ?? 0,
    maximum: sorted.at(-1) ?? 0,
    standardDeviation: Math.sqrt(variance),
    q25: quantile(sorted, 0.25),
    q75: quantile(sorted, 0.75),
  };
}

export function faceComponentGateScore(
  kind: FaceKind,
  component: ComponentGeometry,
  combinedLogits: Float32Array,
  v3Logits: Float32Array,
  v4Logits: Float32Array,
  channelOffset: number,
  size: number,
  segmentationThreshold: number,
  rank: number,
  componentCount: number,
) {
  const gate = GATES[kind];
  if (!gate) return 1;
  const probabilities = component.pixels.map((index) => sigmoid(combinedLogits[channelOffset + index]));
  const v3Probabilities = component.pixels.map((index) => sigmoid(v3Logits[channelOffset + index]));
  const v4Probabilities = component.pixels.map((index) => sigmoid(v4Logits[channelOffset + index]));
  const stats = distribution(probabilities);
  const v3Mean = v3Probabilities.reduce((total, value) => total + value, 0) / component.pixels.length;
  const v4Mean = v4Probabilities.reduce((total, value) => total + value, 0) / component.pixels.length;
  const disagreement = v3Probabilities.reduce((total, value, index) => total + Math.abs(value - v4Probabilities[index]), 0) / component.pixels.length;
  const width = component.maxX - component.minX + 1;
  const height = component.maxY - component.minY + 1;
  const centerX = component.centerX / (size - 1);
  const centerY = component.centerY / (size - 1);
  const features = [
    Math.log1p(component.pixels.length),
    component.pixels.length / (size * size),
    width / size,
    height / size,
    Math.log(Math.max(1e-6, width / height)),
    component.pixels.length / (width * height),
    centerX,
    centerY,
    Math.hypot(centerX - 0.5, centerY - 0.5),
    Number(component.minX === 0 || component.minY === 0 || component.maxX === size - 1 || component.maxY === size - 1),
    stats.mean,
    stats.minimum,
    stats.maximum,
    stats.standardDeviation,
    stats.q25,
    stats.q75,
    probabilities.filter((value) => value >= Math.min(0.99, segmentationThreshold + 0.12)).length / probabilities.length,
    v3Mean,
    v4Mean,
    disagreement,
    rank / Math.max(1, componentCount - 1),
    componentCount / 6,
  ];
  let logit = gate.intercept;
  for (let index = 0; index < features.length; index += 1) {
    logit += ((features[index] - gate.mean[index]) / gate.scale[index]) * gate.coefficient[index];
  }
  return sigmoid(logit);
}

export function acceptFaceComponent(
  kind: FaceKind,
  component: ComponentGeometry,
  combinedLogits: Float32Array,
  v3Logits: Float32Array,
  v4Logits: Float32Array,
  channelOffset: number,
  size: number,
  segmentationThreshold: number,
  rank: number,
  componentCount: number,
) {
  const gate = GATES[kind];
  return !gate || faceComponentGateScore(kind, component, combinedLogits, v3Logits, v4Logits, channelOffset, size, segmentationThreshold, rank, componentCount) >= gate.threshold;
}
